drop function klient(x integer);
drop function zamowienie(x integer);
drop view v_wszystko;
drop view v_klienci;
drop table koszyk;
drop table zamowienie;
drop table klienci;
drop table produkt;
drop table realizacja;
drop table statusy;
drop table adresy;